---
# tasks file for test
- name: installing the apache (or) httpd web server
  ansible.builtin.apt:
    name: apache2
    state: present
- name: copy file with owner and permissions
  ansible.builtin.copy:
    src: index.html
    dest: /var/www/html
    owner: root
    group: root
    mode: '0644'

